# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        none

# Server
source:           ./_source
destination:      ./_web
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001

# Custom vars
current_version:  0.0.1
repo:             http://www.example.cn/
sass_repo:        http://www.example.cn/